export const lipsum = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
  'Fusce tempus erat sed lacus hendrerit vestibulum',
  'Mauris vitae orci ac ex sodales condimentum ut eget tortor',
  'In eleifend risus nec cursus varius',
  'Quisque id pharetra nibh, sed dictum augue',
  'Nunc quis sodales risus',
  'Donec interdum, enim sed fringilla scelerisque, arcu felis venenatis mauris, ac volutpat ante erat sit amet est',
  'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus',
  'Cras eget faucibus mi',
  'Nam vehicula felis nec bibendum volutpat',
  'Phasellus congue, felis nec ullamcorper cursus, ante arcu molestie metus, vel dignissim enim lacus non risus',
  'Nulla eu massa nec odio mollis semper',
  'Vivamus tincidunt vulputate orci, egestas sodales nunc aliquam egestas',
  'Cras sit amet augue et dolor mattis tincidunt',
  'Etiam fringilla finibus odio non gravida',
  'Mauris sodales nibh leo, quis ullamcorper nunc gravida varius',
  'Nam sed dui neque',
  'Nunc urna ipsum, bibendum in tortor a, tincidunt malesuada ipsum',
  'Praesent sed ex ac nisi vehicula pellentesque',
  'Pellentesque euismod et lorem ac ultricies',
  'Pellentesque consectetur velit quis erat maximus egestas',
  'In elementum facilisis nibh, vitae posuere justo sodales condimentum',
  'Nunc quis volutpat mi, aliquet hendrerit dolor',
  'Curabitur suscipit rhoncus metus vel aliquam',
  'Nam purus purus, tristique vitae ultricies eleifend, euismod et metus',
  'Cras dignissim tortor a sem lacinia vulputate',
  'Integer quis dui nec justo maximus venenatis vel sit amet lorem',
  'Integer luctus augue congue lorem semper, quis accumsan neque porttitor',
  'Duis dapibus in metus ut egestas',
  'Nam accumsan ex eget felis fermentum vehicula',
  'Nunc sed iaculis lorem',
  'Sed augue leo, efficitur vitae sapien sed, rutrum pellentesque ex',
  'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas',
  'Sed congue mi justo, ut semper dui porttitor eget',
  'Quisque et nibh leo',
  'Quisque et nisi a turpis placerat sagittis id quis eros',
  'Suspendisse fermentum, diam sit amet bibendum cursus, justo ipsum euismod arcu, et lobortis risus libero a nulla',
  'Aenean dictum metus elit, sed ultrices tortor blandit tristique',
  'Phasellus in blandit erat',
  'Sed mollis urna erat, vitae tempus urna sodales eu',
  'Donec quis laoreet ante',
  'Nam neque nunc, volutpat commodo tellus a, volutpat molestie neque',
  'Ut venenatis nisl non libero porttitor, nec pellentesque felis dictum',
  'Sed a consectetur neque',
  'Donec mattis aliquet ante, vel fermentum mauris aliquet eu',
  'Nulla venenatis est nec ligula viverra vestibulum',
  'Duis mollis urna a venenatis posuere',
  'Aliquam in euismod lorem',
  'Morbi viverra, velit eget malesuada sodales, lectus libero accumsan purus, non eleifend nunc neque nec ante',
  'Etiam non ultricies risus, vel pulvinar leo',
  'Sed eu leo sed enim lacinia porttitor',
  'Suspendisse id tortor leo',
  'Fusce sed vestibulum risus',
  'Sed eu volutpat ante',
  'Quisque imperdiet in justo in tempor',
  'Praesent quis tortor a felis maximus auctor at id dui',
  'Vestibulum fermentum laoreet dolor, vel accumsan tellus cursus sed',
  'Aenean sed luctus justo, a semper turpis',
  'Etiam vel eros sit amet lorem efficitur maximus vel a ex',
  'Nullam fringilla diam ex',
  'Morbi neque nulla, varius a scelerisque in, fermentum volutpat risus'
];
